version: "3.4"
services:
  neko:
    # image: "m1k1o/neko:firefox"
    build:
      context: .
      dockerfile: .docker/firefox/Dockerfile
#    secrets:
#      - server-root-certificate
#      - server-certificate
#         context: './.docker/firefox'
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
      NEKO_NAT1TO1: 127.0.0.1
#secrets:
#  server-root-certificate:
#    file: ./secrets/russian_trusted_root_ca_pem.crt
#  server-certificate:
#    file: ./secrets/russian_trusted_sub_ca_pem.crt
